import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { RouterModule } from '@angular/router';
import { HomeModule } from './home/home.module';
import { SharedModule } from './shared/shared.module';
import { ModalModule } from 'ngx-bootstrap/modal';
import { GalleriaModule } from 'primeng/galleria';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    RouterModule,
    HomeModule,
    SharedModule,
    ModalModule.forRoot(),
    BrowserAnimationsModule,
    GalleriaModule


    // AvatarModule,
    // AvatarGroupModule,
    // AccordionModule,
    // AutoCompleteModule,
    // BadgeModule,
    // BreadcrumbModule,
    // BlockUIModule,
    // ButtonModule,
    // CalendarModule,
    // CarouselModule,
    // CascadeSelectModule,
    // CheckboxModule,
    // ChipsModule,
    // ChipModule,
    // ColorPickerModule,
    // ConfirmDialogModule,
    // ConfirmPopupModule,
    // ContextMenuModule,
    // VirtualScrollerModule,
    // DataViewModule,
    // DialogModule,
    // DividerModule,
    // DockModule,
    // DropdownModule,
    // DynamicDialogModule,
    // FieldsetModule,
    // FileUploadModule,
    // GalleriaModule,
    // InplaceModule,
    // InputMaskModule,
    // InputSwitchModule,
    // InputTextModule,
    // InputTextareaModule,
    // InputNumberModule,
    // ImageModule,
    // KnobModule,
    // ListboxModule,
    // MegaMenuModule,
    // MenuModule,
    // MenubarModule,
    // MessageModule,
    // MessagesModule,
    // MultiSelectModule,
    // OrganizationChartModule,
    // OrderListModule,
    // OverlayPanelModule,
    // PaginatorModule,
    // PanelModule,
    // PanelMenuModule,
    // PasswordModule,
    // PickListModule,
    // ProgressSpinnerModule,
    // ProgressBarModule,
    // RadioButtonModule,
    // RatingModule,
    // SelectButtonModule,
    // SidebarModule,
    // ScrollerModule,
    // ScrollPanelModule,
    // ScrollTopModule,
    // SkeletonModule,
    // SlideMenuModule,
    // SliderModule,
    // SpeedDialModule,
    // SpinnerModule,
    // SplitterModule,
    // SplitButtonModule,
    // StepsModule,
    // TableModule,
    // TabMenuModule,
    // TabViewModule,
    // TagModule,
    // TerminalModule,
    // TieredMenuModule,
    // TimelineModule,
    // ToastModule,
    // ToggleButtonModule,
    // ToolbarModule,
    // TooltipModule,
    // TriStateCheckboxModule,
    // TreeModule,
    // TreeSelectModule,
    // TreeTableModule,
    // AnimateModule,
    // CardModule,
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
